let buttonsenabled = true
let battlemessage = ''
let protected = false
let playermove = null
let enemymove = null
let p1movehistory = []
let p2movehistory = []
let p1movehit = null
let p2movehit = null
let turncounter = 0
let deadp1 = null
let deadp2 = null
let p1invul = null
let p2invul = null
let p2nextmove = null
let statused = null
let isconfused = null
let paralysed = null
let endturn = false
let gameon = true
let acc2hit = false
let playerqueue = []
let rivalqueue = []
let cantflee = false
let queue = []

const types = [
    /* Normal 0*/[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5, 0, 1, 1, 0.5, 1, 1],
    /* Fire 1*/[1, 0.5, 0.5, 1, 2, 2, 1, 1, 1, 1, 1, 2, 0.5, 1, 0.5, 1, 2, 1, 1],
    /* Water 2*/[1, 2, 0.5, 1, 0.5, 1, 1, 1, 2, 1, 1, 1, 2, 1, 0.5, 1, 1, 1, 1],
    /* Grass 3*/[1, 0.5, 2, 1, 0.5, 1, 1, 0.5, 2, 0.5, 1, 1, 0.5, 1, 0.5, 1, 0.5, 1, 1],
    /* Electric 4*/[1, 1, 2, 0.5, 0.5, 1, 1, 1, 0, 2, 1, 1, 1, 1, 0.5, 1, 1, 1, 1],
    /* Ice 5*/[1, 0.5, 0.5, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 0.5, 1, 0.5, 1, 1],
    /* Fighting 6*/[2, 1, 1, 1, 1, 2, 1, 0.5, 1, 0.5, 0.5, 0.5, 2, 0, 1, 2, 2, 0.5, 1],
    /* Poison 7*/[1, 1, 1, 1, 2, 1, 1, 0.5, 0.5, 1, 1, 1, 0.5, 0.5, 1, 1, 0, 2, 1],
    /* Ground 8*/[1, 2, 1, 2, 0.5, 1, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1, 2, 1, 1],
    /* Flying 9*/[1, 1, 1, 0.5, 2, 1, 2, 1, 1, 1, 1, 1, 0.5, 1, 2, 1, 0.5, 1, 1],
    /* Psychic 10*/[1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 0.5, 1, 1, 1, 1, 0, 0.5, 1, 1],
    /* Bug 11*/[1, 0.5, 1, 1, 2, 1, 0.5, 0.5, 1, 0.5, 2, 1, 1, 0.5, 1, 2, 0.5, 0.5, 1],
    /* Rock 12*/[1, 2, 1, 1, 1, 2, 0.5, 1, 0.5, 2, 1, 2, 1, 1, 2, 1, 0.5, 1, 1],
    /* Ghost 13*/[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 0.5, 1, 1, 1],
    /* Dragon 14*/[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0.5, 0, 1],
    /* Dark 15*/[1, 1, 1, 1, 1, 1, 0.5, 1, 1, 1, 2, 1, 1, 2, 1, 0.5, 1, 0.5, 1],
    /* Steel 16*/[1, 0.5, 0.5, 0.5, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0.5, 2, 1],
    /* Fairy 17*/[1, 0.5, 1, 1, 1, 1, 2, 0.5, 1, 1, 1, 1, 1, 1, 2, 2, 0.5, 1, 1],
    /* No Type 18*/[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
]

const statstates = [
    2 / 8, 2 / 7, 2 / 6, 2 / 5, 2 / 4, 2 / 3, 2 / 2, 3 / 2, 4 / 2, 5 / 2, 6 / 2, 7 / 2, 8 / 2
]

const statstates2 = [
    3 / 9, 3 / 8, 3 / 7, 3 / 6, 3 / 5, 3 / 4, 3 / 3, 4 / 3, 5 / 3, 6 / 3, 7 / 3, 8 / 3, 9 / 3
]

let global = {
    trickroom: false
}

let player = {
    atk: 6,
    def: 6,
    spa: 6,
    spd: 6,
    spe: 6,
    acc: 6,
    eva: 6,
    cnf: false,  // Confused
    spk: false,  // Spikes
    tspk: false, // Toxic Spikes
    strk: false, // Stealth Rock
    stwb: false, // Sticky Web
    auveil: 0,
    reflect: 0,
    lscreen: 0,
    txc: 1,      // toxic counter
    inlove: false,
    dynamax: false,
}

let rival = {
    atk: 6,
    def: 6,
    spa: 6,
    spd: 6,
    spe: 6,
    acc: 6,
    eva: 6,
    cnf: false,
    spk: false,
    tspk: false,
    strk: false,
    stwb: false,
    auveil: 0,
    reflect: 0,
    lscreen: 0,
    txc: 1,
    inlove: false,
    dynamax: false,
}

let weather = {
    weather: '',
    image: '',
    images: {
        sun: '<img src="pictures/status/sun.png" style="width: 5vh; height: auto;" alt="">',
        rain: '<img src="pictures/status/rain.png" style="width: 5vh; height: auto;" alt="">',
        sandstorm: '<img src="pictures/status/sandstorm.png" style="width: 5vh; height: auto;" alt="">',
        hail: '<img src="pictures/status/snow.png" style="width: 5vh; height: auto;" alt="">',
    }
}

const statusimages = {
    brn: '<img src="pictures/status/brnimage.png" style="width: 5vh; height: auto;" alt="">',
    par: '<img src="pictures/status/parimage.png" style="width: 6vh; height: auto;" alt="">',
    psn: '<img src="pictures/status/psnimage.png" style="width: 6vh; height: auto;" alt="">',
    tox: '<img src="pictures/status/psnimage.png" style="width: 6vh; height: auto;" alt="">',
    slp: '<img src="pictures/status/slpimage.png" style="width: 6vh; height: auto;" alt="">',
    frz: '<img src="pictures/status/frzimage.png" style="width: 6vh; height: auto;" alt="">',
}

const typecolors = ['hsl(58, 20%, 56%)',
    'hsl(25, 84%, 56%)',
    'hsl(220, 82%, 66%)',
    'hsl(97, 52%, 53%)',
    'hsl(48, 92%, 57%)',
    'hsl(177, 46%, 71%)',
    'hsl(2, 65%, 45%)',
    'hsl(301, 44%, 44%)',
    'hsl(43, 68%, 64%)',
    'hsl(255, 80%, 75%)',
    'hsl(341, 93%, 65%)',
    'hsl(67, 75%, 41%)',
    'hsl(50, 54%, 46%)',
    'hsl(266, 26%, 46%)',
    'hsl(257, 97%, 59%)',
    'hsl(24, 23%, 35%)',
    'hsl(240, 19%, 76%)',
    'hsl(330, 49%, 68%)'
]

const items = [
    {
        name: 'Focus Sash',
        effect: 'fullhpdmgsurvival',
        trigger: 'fullhpko',
        cd: false,
    }
]

const abilities = [
    {
        name: 'Intimidate',
        trigger: 'onentry',
        cd: false,
        effect: 'atkdown',
    },
    {
        name: 'Sturdy',
        effect: 'fullhpdmgsurvival',
        trigger: 'fullhpko',
        cd: false,
    }
]

const moves = [
    {
        name: 'Struggle',
        type: 18,
        dmg: 50,
        acc: 0,
        movetype: 'damagewithrecoil',
        effect: 0.5,
        pp: 0,
    },
    {
        name: '10,000,000 Volt Thunderbolt',
        type: 4,
        acc: 0,
        movetype: 'damage',
        dmg: 195,
        pp: 1,
        dmgtype: 'spe',
        crit: 2,
    },
    {
        name: 'Absorb',
        type: 3,
        acc: 0,
        movetype: 'dmgheal',
        dmg: 20,
        pp: 20,
        dmgtype: 'spe',
        value: 0.5,
    },
    {
        name: 'Accelrock',
        type: 12,
        acc: 100,
        movetype: 'damage',
        dmg: 40,
        acc: 100,
        priority: 1,
        dmgtype: 'phy',
        pp: 20,
    },
    {
        name: 'Acid',
        type: 7,
        acc: 100,
        movetype: 'damage',
        dmg: 40,
        effect2: 'stat',
        acc2: 10,
        effecttype: ['spd'],
        effect: [-1],
        who: ['you'],
        dmgtype: 'spe',
        pp: 30,
    },
    {
        name: 'Acid Spray',
        type: 7,
        acc: 100,
        movetype: 'damage',
        dmg: 40,
        effect2: 'stat',
        acc2: 0,
        effecttype: ['spd'],
        effect: [-2],
        who: ['you'],
        dmgtype: 'spe',
        pp: 20,
    },
    {
        name: 'Acrobatics',
        type: 9,
        acc: 100,
        movetype: 'acrobatics',
        dmg: 55,
        pp: 35,
        dmgtype: 'phy',
    },
    {
        name: 'Acupressure',
        type: 0,
        acc: 0,
        effect: [2],
        who: ['me'],
        movetype: 'acupressure',
        pp: 30,
    },
    {
        name: 'Aerial Ace',
        type: 9,
        acc: 0,
        movetype: 'damage',
        dmg: 60,
        pp: 20,
        dmgtype: 'phy',
    },
    {
        name: 'After You',
        type: 0,
        acc: 0,
        movetype: 'afteryou',
        pp: 15,
    },
    {
        name: 'Aeroblast',
        type: 9,
        acc: 95,
        movetype: 'damage',
        dmg: 100,
        pp: 5,
        dmgtype: 'spe',
        crit: 1,
    },
    {
        name: 'Agility',
        type: 10,
        acc: 0,
        movetype: 'stat',
        effecttype: ['spe'],
        effect: [2],
        who: ['me'],
        pp: 30,
    },
    {
        name: 'Air Cutter',
        type: 9,
        acc: 60,
        movetype: 'damage',
        dmg: 95,
        pp: 25,
        dmgtype: 'spe',
        crit: 1,
    },
    {
        name: 'Air Slash',
        type: 9,
        acc: 75,
        movetype: 'damage',
        dmg: 95,
        pp: 15,
        dmgtype: 'spe',
        effect2: 'flinch',
        acc2: 20,
    },
    {
        name: 'Alluring Voice',
        type: 17,
        acc: 100,
        movetype: 'damage',
        dmg: 80,
        pp: 10,
        dmgtype: 'spe',
        effect2: 'alluringvoice',
        acc2: 0,
    },
    {
        name: 'Ally Switch',
        type: 10,
        acc: 0,
        movetype: 'failed',
        pp: 15,
        priority: 2,
    },
    {
        name: 'Amnesia',
        type: 10,
        acc: 0,
        movetype: 'stat',
        effecttype: ['spd'],
        effect: [2],
        who: ['me'],
        pp: 20,
    },
    {
        name: 'Anchor Shot',
        type: 16,
        acc: 100,
        movetype: 'damage',
        dmg: 80,
        pp: 20,
        dmgtype: 'spe',
        effect2: 'trapped',
        acc2: 0,
    },
    {
        name: 'Ancient Power',
        type: 12,
        acc: 100,
        movetype: 'damage',
        dmg: 60,
        pp: 5,
        dmgtype: 'spe',
        effect2: 'stat',
        effecttype: ['atk', 'def', 'spa', 'spd', 'spe'],
        effect: [1, 1, 1, 1, 1],
        who: ['me', 'me', 'me', 'me', 'me'],
        acc2: 10,
    },
    {
        name: 'Apple Acid',
        type: 3,
        acc: 100,
        movetype: 'damage',
        dmg: 80,
        pp: 10,
        dmgtype: 'spe',
        effect2: 'stat',
        effecttype: ['spd'],
        effect: [-1],
        who: ['you'],
        acc2: 0,
    },
    {
        name: 'Aqua Cutter',
        type: 2,
        acc: 100,
        movetype: 'damage',
        dmg: 70,
        pp: 20,
        dmgtype: 'spe',
        crit: 1,
    },
    {
        name: 'Aqua Step',
        type: 2,
        acc: 100,
        movetype: 'damage',
        dmg: 80,
        pp: 10,
        dmgtype: 'spe',
        effect2: 'stat',
        effecttype: ['spe'],
        effect: [1],
        who: ['me'],
        acc2: 0,
    },
    {
        name: 'Aqua Tail',
        type: 2,
        acc: 90,
        movetype: 'damage',
        dmg: 90,
        pp: 10,
        dmgtype: 'spe',
    },
    {
        name: 'Arm Thrust',
        type: 6,
        acc: 100,
        movetype: 'multidmg',
        dmg: 15,
        dmgtype: 'phy',
        pp: 20,
    },
    {
        name: 'Armor Cannon',
        type: 1,
        acc: 100,
        movetype: 'damage',
        dmg: 80,
        pp: 5,
        dmgtype: 'spe',
        effect2: 'stat',
        effecttype: ['def', 'spd'],
        effect: [-1, -1],
        who: ['me', 'me'],
        acc2: 0,
    },
    {
        name: 'Aromatherapy',
        type: 2,
        acc: 0,
        movetype: 'healallstatus',
        pp: 5,
    },
    {
        name: 'Aromatic Mist',
        type: 17,
        acc: 0,
        movetype: 'failed',
        pp: 20,
    },
    {
        name: 'Assist',
        type: 0,
        acc: 0,
        movetype: 'failed',
        pp: 20,
    },
    {
        name: 'Assurance',
        type: 0,
        acc: 100,
        movetype: 'damage',
        failed: 'failed',
        dmg: 60,
        pp: 10,
        dmgtype: 'phy',
    },
    {
        name: 'Astonish',
        type: 13,
        acc: 100,
        movetype: 'damage',
        dmg: 30,
        pp: 15,
        dmgtype: 'phy',
        effect2: 'flinch',
        acc2: 30,
    },
    {
        name: 'Astral Barrage',
        type: 13,
        acc: 100,
        movetype: 'damage',
        dmg: 120,
        pp: 5,
        dmgtype: 'spe',
    },
    {
        name: 'Attack Order',
        type: 11,
        acc: 100,
        movetype: 'damage',
        dmg: 90,
        pp: 15,
        dmgtype: 'phy',
        crit: 1,
    },
    {
        name: 'Attract',
        type: 0,
        acc: 100,
        movetype: 'infatuation',     
        pp: 15,
    },
    {
        name: 'Aura Sphere',
        type: 6,
        acc: 0,
        movetype: 'damage',
        dmg: 80,
        pp: 20,
        dmgtype: 'spe',
    },
    {
        name: 'Aura Wheel',
        type: 0,
        acc: 100,
        movetype: 'damage',         // Hva er en morpeko??
        dmg: 40,
        pp: 35,
        dmgtype: 'phy',
    },
    {
        name: 'Aurora Beam',
        type: 5,
        acc: 100,
        movetype: 'damage',
        dmg: 65,
        pp: 20,
        dmgtype: 'spe',
        effect2: 'stat',
        acc2: 10,
        effecttype: ['atk'],
        effect: [-1],
        who: ['you'],
    },
    {
        name: 'Aurora Veil',
        type: 17,
        acc: 0,
        movetype: 'auroraveil',        
        pp: 20,
    },
    {
        name: 'Autotomize',        
        type: 16,
        acc: 0,
        movetype: 'autotomize',         
        effecttype: ['spe'],
        effect: [2],
        who: ['me'],
        pp: 15,
    },
    {
        name: 'Avalanche',
        type: 5,
        acc: 100,
        movetype: 'avalanche',
        dmg: 60,
        pp: 10,
        dmgtype: 'phy',
        priority: -1,
    },
    {
        name: 'Axe Kick',
        type: 6,
        acc: 90,
        movetype: 'losehpifmiss',
        hploss: 0.5,
        dmg: 120,
        pp: 10,
        dmgtype: 'phy',
    },
    {
        name: 'Baby-Doll Eyes',
        type: 17,
        acc: 100,
        movetype: 'stat',
        effecttype: ['atk'],
        effect: [-1],
        who: ['you'],
        pp: 30,
        priority: 1,
    },
    {
        name: 'Baddy Bad',
        type: 0,
        acc: 100,
        movetype: 'damage',        
        effect2: 'screen',
        screentype: 'reflect',
        dmg: 80,
        pp: 15,
        dmgtype: 'spe',
    },
    {
        name: 'Baneful Bunker',
        type: 7,
        acc: 0,
        movetype: 'banefulbunker',
        priority: 4,
        pp: 10,
    },
    {
        name: 'Barb Barrage',
        type: 7,
        acc: 100,
        movetype: 'barbbarrage',
        dmg: 60,
        pp: 10,
        effect2: 'status',
        statustype: 'brn',
        effect: true,
        dmgtype: 'phy',
    },
    {
        name: 'Barrage',
        type: 0,
        acc: 85,
        movetype: 'multidmg',
        dmg: 15,
        dmgtype: 'phy',
        pp: 20,
    },
    {
        name: 'Barrier',
        type: 10,
        acc: 0,
        movetype: 'stat',
        effecttype: ['def'],
        effect: [2],
        who: ['me'],
        pp: 20,
    },
    {
        name: 'Baton Pass',         // må imlpementere alt som kan påvirke det først
        type: 0,
        acc: 100,
        movetype: 'damage',
        dmg: 40,
        pp: 35,
        dmgtype: 'phy',
    },
    {
        name: 'Beak Blast',             // Wtf
        type: 0,
        acc: 100,
        movetype: 'damage',
        dmg: 40,
        pp: 35,
        dmgtype: 'phy',
    },
    {
        name: 'Beat Up',
        type: 15,
        acc: 100,
        movetype: 'beatup',
        dmg: null,
        pp: 10,
        dmgtype: 'phy',
    },
    {
        name: 'Behemoth Bash',     
        type: 16,
        acc: 100,
        movetype: 'behemoth',
        dmg: 100,
        pp: 5,
        dmgtype: 'phy',
    },
    {
        name: 'Behemoth Blade',     
        type: 0,
        acc: 100,
        movetype: 'behemoth',
        dmg: 100,
        pp: 35,
        dmgtype: 'phy',
    },
    {
        name: 'Belch',
        type: 0,
        acc: 90,
        movetype: 'belch',
        dmg: 120,
        pp: 10,
        dmgtype: 'spe',
    },
    {
        name: 'Belly Drum',
        type: 0,
        acc: 0,
        movetype: 'bellydrum',
        pp: 10,
    },
    {
        name: 'Bestow',
        type: 0,
        acc: 0,
        movetype: 'bestow',
        pp: 15,
    },
    {
        name: 'Tackle',
        type: 0,
        acc: 100,
        movetype: 'damage',
        dmg: 40,
        pp: 35,
        dmgtype: 'phy',
    },
    {
        name: 'Growl',
        type: 0,
        acc: 0,
        movetype: 'stat',
        effecttype: ['atk'],
        effect: [-1],
        who: ['you'],
        pp: 10,
    },
    {
        name: 'U Turn',
        type: 11,
        acc: 100,
        movetype: 'damage',
        effect2: 'switchuser',
        acc2: 0,
        dmg: 70,
        pp: 35,
        dmgtype: 'phy',
        pp: 10,
    },
    {
        name: 'Protect',
        type: 0,
        acc: 0,
        movetype: 'protect',
        priority: 4,
        pp: 10,
    },
    {
        name: 'Rock Blast',
        type: 12,
        acc: 90,
        movetype: 'multidmg',
        dmg: 25,
        dmgtype: 'phy',
        pp: 20,
    },
    {
        name: 'Giga Impact',
        type: 0,
        acc: 90,
        movetype: 'damage',
        turn2: {
            movetype: 'recharge'
        },
        dmg: 150,
        pp: 35,
        dmgtype: 'phy',
        pp: 10,
    },
    {
        name: 'Fly',
        type: 9,
        movetype: 'invul',
        pp: 10,
        acc: 100,
        turn2: {
            name: 'Fly',
            type: 9,
            dmg: 90,
            acc: 95,
            movetype: 'damage',
            dmgtype: 'phy',
        },
    },
    {
        name: 'Toxic',
        type: 7,
        acc: 0,
        movetype: 'status',
        statustype: 'tox',
        effect: true,
        pp: 10,
    },
    {
        name: 'Power Up Punch',
        type: 6,
        acc: 0,
        movetype: 'damage',
        dmg: 40,
        effect2: 'stat',
        acc2: 100,
        crit: 0,
        effecttype: ['atk'],
        effect: [1],
        who: ['me'],
        dmgtype: 'phy',
        pp: 15,
    },
    {
        name: 'Recover',
        type: 0,
        acc: 0,
        movetype: 'heal',
        healtype: '%',
        heal: 0.5,
        pp: 10,
    },
    {
        name: 'Quick Attack',
        type: 0,
        acc: 100,
        movetype: 'damage',
        dmg: 40,
        acc: 100,
        priority: 1,
        dmgtype: 'phy',
        pp: 10,
    },
    {
        name: 'Swords Dance',
        type: 0,
        acc: 0,
        movetype: 'stat',
        effecttype: ['atk'],
        effect: [2],
        who: ['me'],
        pp: 10,
    },
    {
        name: 'Explosion',
        type: 0,
        dmg: 250,
        acc: 100,
        acc2: 0,
        movetype: 'damage',
        effect2: 'suicide',
        dmgtype: 'phy',
        pp: 10,
    },
    {
        name: 'Smokescreen',
        type: 13,
        acc: 0,
        movetype: 'stat',
        effecttype: ['acc'],
        effect: [-1],
        who: ['you'],
        pp: 10,
    },
    {
        name: 'Will o Wisp',
        type: 1,
        acc: 85,
        movetype: 'status',
        statustype: 'brn',
        effect: true,
        pp: 10,
    },
    {
        name: 'Sandstorm',
        type: 3,
        acc: 0,
        movetype: 'weatherchange',
        weather: 'sandstorm',
        pp: 10,
    },
    {
        name: 'Rain Dance',
        type: 2,
        acc: 0,
        movetype: 'weatherchange',
        weather: 'rain',
        pp: 10,
    },
    {
        name: 'Lunar Dance',
        type: 0,
        acc: 0,
        movetype: 'statusheal',
        statustype: '',
        effect: false,
        pp: 10,
    },
    {
        name: 'Curse',
        type: 13,
        acc: 0,
        movetype: 'stat',
        effecttype: ['spe', 'atk', 'def'],
        effect: [-1, 1, 1],
        who: ['me', 'me', 'me'],
        pp: 10,
    },
    {
        name: 'Rock Throw',
        type: 12,
        acc: 90,
        movetype: 'damage',
        dmg: 50,
        dmgtype: 'phy',
        pp: 10,
    },
    {
        name: 'Bite',
        type: 15,
        acc: 100,
        movetype: 'damage',
        dmg: 60,
        effect2: 'flinch',
        acc2: 20,
        dmgtype: 'phy',
        pp: 10,
    },
    {
        name: 'Spikes',
        type: 8,
        acc: 0,
        movetype: 'sethazard',
        effect: 'spk',
        pp: 20,
    },
    {
        name: 'Toxic Spikes',
        type: 7,
        acc: 0,
        movetype: 'sethazard',
        effect: 'tspk',
        pp: 20,
    },
    {
        name: 'Stealth Rock',
        type: 12,
        acc: 0,
        movetype: 'sethazard',
        effect: 'strk',
        pp: 20,
    },
    {
        name: 'Sticky Web',
        type: 11,
        acc: 0,
        movetype: 'sethazard',
        effect: 'stwb',
        pp: 20,
    },
    {
        name: 'Solar Beam',
        type: 3,
        movetype: 'charge',
        turn2: {
            name: 'Solar Beam',
            type: 3,
            dmg: 120,
            acc: 100,
            movetype: 'damage',
            dmgtype: 'spe',
            pp: 20,
        }
    },
    {
        name: 'Dig',
        type: 8,
        dmg: 80,
        acc: 100,
        movetype: 'damage',
        effect: 'invulthendmg',
        pp: 20,
    },
    {
        name: 'Confuse Ray',
        type: 13,
        acc: 100,
        movetype: 'confuse',
        pp: 20,
    },
    {
        name: 'Trick Room',
        type: 10,
        acc: 0,
        movetype: 'trickroom',
        pp: 5,
        priority: -7,
    },
    {
        name: 'Double Edge',
        type: 0,
        dmg: 120,
        acc: 100,
        movetype: 'damagewithrecoil',
        effect: 0.33,
        pp: 20,
    },
]

let pokemon = [
    {
        name: "Dwebble",
        avatar: `<img style="height: auto; width: 20vh" src="pictures/pokemon/dwebble.png" alt="">`,
        url: 'pictures/pokemon/dwebble.png',
        maxhp: 10000,
        hp: 10000,
        atk: 10,
        def: 10,
        spa: 10,
        spd: 10,
        spe: 10,
        status: '',
        move: [60, 7, 9, 3],
        pp: [],
        type1: 11,
        type2: 12,
        sex: 'male',
        weight: 14.5, 
        ability: JSON.parse(JSON.stringify(abilities[1])),
        item: JSON.parse(JSON.stringify(items[0])),
        id: 0,
    },
    {
        name: "Charmander",
        avatar: `<img style="height: auto; width: 20vh" src="pictures/pokemon/charmander.png" alt="">`,
        url: 'pictures/pokemon/charmander.png',
        maxhp: 3,
        hp: 3,
        atk: 11,
        def: 8,
        spa: 13,
        spd: 10,
        spe: 1,
        status: '',
        move: [1, 1, 1, 1],
        pp: [],
        type1: 1,
        type2: 18,
        sex: 'male',
        weight: 14.5, 
        ability: JSON.parse(JSON.stringify(abilities[1])),
        item: JSON.parse(JSON.stringify(items[0])),
        id: 1
    },
    {
        name: "kek",
        avatar: `<img style="height: auto; width: 20vh" src="pictures/pokemon/charmander.png" alt="">`,
        maxhp: 3,
        hp: 3,
        atk: 11,
        def: 8,
        spa: 13,
        spd: 10,
        spe: 1,
        status: '',
        move: [1, 2, 3, 4],
        pp: [],
        type1: 1,
        type2: 18,
        sex: 'female',
        weight: 14.5, 
        ability: JSON.parse(JSON.stringify(abilities[1])),
        item: null,
        id: 2
    },
]

let p1 = {
    name: 'Red',
    avatar: `<div>
    <img style="height: 20vh; width: auto" src="https://archives.bulbagarden.net/media/upload/thumb/d/d3/Lets_Go_Pikachu_Eevee_Red.png/250px-Lets_Go_Pikachu_Eevee_Red.png" alt="}">
    `,
    pokemon: [pokemon[0], pokemon[1], pokemon[1], pokemon[0]].map(p => JSON.parse(JSON.stringify(p)))
}

let p2 = {
    name: 'Cynthia',
    avatar: `
    <img style="height: 20vh; width: auto" src="https://www.serebii.net/pokemonmasters/syncpairs/cynthia.png" alt="">`,
    pokemon: [pokemon[2], pokemon[2], pokemon[0]].map(p => JSON.parse(JSON.stringify(p)))
}

const movesounds = {
    tackle: new Audio('sounds/moves/tackle.mp3'),
    curse: new Audio('sounds/moves/curse.mp3'),
    smokescreen: new Audio('sounds/moves/smokescreen.mp3'),
    statup: new Audio('sounds/moves/statup.mp3'),
    statdown: new Audio('sounds/moves/statdown.mp3'),
    protect: new Audio('sounds/moves/protect.mp3'),
    gigaimpact: new Audio('sounds/moves/gigaimpact.mp3'),
    rockblast: new Audio('sounds/moves/rockblast.mp3'),
    raindance: new Audio('sounds/moves/raindance.mp3'),
    sandstorm: new Audio('sounds/moves/sandstorm.mp3'),
    bite: new Audio('sounds/moves/sandstorm.mp3'),
    fly: new Audio('sounds/moves/fly.mp3'),
    rockblast: new Audio('sounds/moves/tackle.mp3'),
    uturn: new Audio('sounds/moves/tackle.mp3'),
}




