const moves = [
    {
        name: 'Struggle',
        type: 18,
        dmg: 50,
        acc: 0,
        movetype: 'damagewithrecoil',
        effect: 0.5,
        pp: 0,
    },
    {
        name: '10,000,000 Volt Thunderbolt',
        type: 4,
        acc: 0,
        movetype: 'damage',
        dmg: 195,
        pp: 1,
        dmgtype: 'spe',
        crit: 2,
    },
    {
        name: 'Absorb',
        type: 3,
        acc: 100,
        movetype: 'dmgheal',
        dmg: 20,
        pp: 20,
        dmgtype: 'spe',
        value: 0.5,
    },
    {
        name: 'Accelrock',
        type: 12,
        acc: 100,
        movetype: 'damage',
        dmg: 40,
        acc: 100,
        priority: 1,
        dmgtype: 'phy',
        pp: 20,
    },
    {
        name: 'Acid',
        type: 7,
        acc: 100,
        movetype: 'damage',
        dmg: 40,
        effect2: 'stat',
        acc2: 10,
        effecttype: ['spd'],
        effect: [-1],
        who: ['you'],
        dmgtype: 'spe',
        pp: 30,
    },
    {
        name: 'Acid Spray',
        type: 7,
        acc: 100,
        movetype: 'damage',
        dmg: 40,
        effect2: 'stat',
        acc2: 0,
        effecttype: ['spd'],
        effect: [-2],
        who: ['you'],
        dmgtype: 'spe',
        pp: 20,
    },
    {
        name: 'Acrobatics',
        type: 9,
        acc: 100,
        movetype: 'acrobatics',
        dmg: 55,
        pp: 35,
        dmgtype: 'phy',
    },
    {
        name: 'Acupressure',
        type: 0,
        acc: 0,
        effect: [2],
        who: ['me'],
        movetype: 'acupressure',
        pp: 30,
    },
    {
        name: 'Aerial Ace',
        type: 9,
        acc: 0,
        movetype: 'damage',
        dmg: 60,
        pp: 20,
        dmgtype: 'phy',
    },
    {
        name: 'After You',
        type: 0,
        acc: 0,
        movetype: 'afteryou',
        pp: 15,
    },
    {
        name: 'Aeroblast',
        type: 9,
        acc: 95,
        movetype: 'damage',
        dmg: 100,
        pp: 5,
        dmgtype: 'spe',
        crit: 1,
    },
    {
        name: 'Agility',
        type: 10,
        acc: 0,
        movetype: 'stat',
        effecttype: ['spe'],
        effect: [2],
        who: ['me'],
        pp: 30,
    },
    {
        name: 'Air Cutter',
        type: 9,
        acc: 60,
        movetype: 'damage',
        dmg: 95,
        pp: 25,
        dmgtype: 'spe',
        crit: 1,
    },
    {
        name: 'Air Slash',
        type: 9,
        acc: 75,
        movetype: 'damage',
        dmg: 95,
        pp: 15,
        dmgtype: 'spe',
        effect2: 'flinch',
        acc2: 20,
    },
    {
        name: 'Alluring Voice',
        type: 17,
        acc: 100,
        movetype: 'damage',
        dmg: 80,
        pp: 10,
        dmgtype: 'spe',
        effect2: 'alluringvoice',
        acc2: 0,
    },
    {
        name: 'Ally Switch',
        type: 10,
        acc: 0,
        movetype: 'failed',
        pp: 15,
        priority: 2,
    },
    {
        name: 'Amnesia',
        type: 10,
        acc: 0,
        movetype: 'stat',
        effecttype: ['spd'],
        effect: [2],
        who: ['me'],
        pp: 20,
    },
    {
        name: 'Anchor Shot',
        type: 16,
        acc: 100,
        movetype: 'damage',
        dmg: 80,
        pp: 20,
        dmgtype: 'spe',
        effect2: 'trapped',
        acc2: 0,
    },
    {
        name: 'Ancient Power',
        type: 12,
        acc: 100,
        movetype: 'damage',
        dmg: 60,
        pp: 5,
        dmgtype: 'spe',
        effect2: 'stat',
        effecttype: ['atk', 'def', 'spa', 'spd', 'spe'],
        effect: [1, 1, 1, 1, 1],
        who: ['me', 'me', 'me', 'me', 'me'],
        acc2: 10,
    },
    {
        name: 'Apple Acid',
        type: 3,
        acc: 100,
        movetype: 'damage',
        dmg: 80,
        pp: 10,
        dmgtype: 'spe',
        effect2: 'stat',
        effecttype: ['spd'],
        effect: [-1],
        who: ['you'],
        acc2: 0,
    },
    {
        name: 'Aqua Cutter',
        type: 2,
        acc: 100,
        movetype: 'damage',
        dmg: 70,
        pp: 20,
        dmgtype: 'spe',
        crit: 1,
    },
    {
        name: 'Aqua Step',
        type: 2,
        acc: 100,
        movetype: 'damage',
        dmg: 80,
        pp: 10,
        dmgtype: 'spe',
        effect2: 'stat',
        effecttype: ['spe'],
        effect: [1],
        who: ['me'],
        acc2: 0,
    },
    {
        name: 'Aqua Tail',
        type: 2,
        acc: 90,
        movetype: 'damage',
        dmg: 90,
        pp: 10,
        dmgtype: 'spe',
    },
    {
        name: 'Arm Thrust',
        type: 6,
        acc: 100,
        movetype: 'multidmg',
        dmg: 15,
        dmgtype: 'phy',
        pp: 20,
    },
    {
        name: 'Armor Cannon',
        type: 1,
        acc: 100,
        movetype: 'damage',
        dmg: 80,
        pp: 5,
        dmgtype: 'spe',
        effect2: 'stat',
        effecttype: ['def', 'spd'],
        effect: [-1, -1],
        who: ['me', 'me'],
        acc2: 0,
    },
    {
        name: 'Aromatherapy',
        type: 2,
        acc: 0,
        movetype: 'healallstatus',
        pp: 5,
    },
    {
        name: 'Aromatic Mist',
        type: 17,
        acc: 0,
        movetype: 'failed',
        pp: 20,
    },
    {
        name: 'Assist',
        type: 0,
        acc: 0,
        movetype: 'failed',
        pp: 20,
    },
    {
        name: 'Assurance',
        type: 0,
        acc: 100,
        movetype: 'damage',
        failed: 'failed',
        dmg: 60,
        pp: 10,
        dmgtype: 'phy',
    },
    {
        name: 'Astonish',
        type: 13,
        acc: 100,
        movetype: 'damage',
        dmg: 30,
        pp: 15,
        dmgtype: 'phy',
        effect2: 'flinch',
        acc2: 30,
    },
    {
        name: 'Astral Barrage',
        type: 13,
        acc: 100,
        movetype: 'damage',
        dmg: 120,
        pp: 5,
        dmgtype: 'spe',
    },
    {
        name: 'Attack Order',
        type: 11,
        acc: 100,
        movetype: 'damage',
        dmg: 90,
        pp: 15,
        dmgtype: 'phy',
        crit: 1,
    },
    {
        name: 'Attract',
        type: 0,
        acc: 100,
        movetype: 'infatuation',     
        pp: 15,
    },
    {
        name: 'Aura Sphere',
        type: 6,
        acc: 0,
        movetype: 'damage',
        dmg: 80,
        pp: 20,
        dmgtype: 'spe',
    },
    {
        name: 'Aura Wheel',
        type: 0,
        acc: 100,
        movetype: 'damage',         // Hva er en morpeko??
        dmg: 40,
        pp: 35,
        dmgtype: 'phy',
    },
    {
        name: 'Aurora Beam',
        type: 5,
        acc: 100,
        movetype: 'damage',
        dmg: 65,
        pp: 20,
        dmgtype: 'spe',
        effect2: 'stat',
        acc2: 10,
        effecttype: ['atk'],
        effect: [-1],
        who: ['you'],
    },
    {
        name: 'Aurora Veil',
        type: 17,
        acc: 0,
        movetype: 'auroraveil',        
        pp: 20,
    },
    {
        name: 'Autotomize',        
        type: 16,
        acc: 0,
        movetype: 'autotomize',         
        effecttype: ['spe'],
        effect: [2],
        who: ['me'],
        pp: 15,
    },
    {
        name: 'Avalanche',
        type: 5,
        acc: 100,
        movetype: 'avalanche',
        dmg: 60,
        pp: 10,
        dmgtype: 'phy',
        priority: -1,
    },
    {
        name: 'Axe Kick',
        type: 6,
        acc: 90,
        movetype: 'losehpifmiss',
        hploss: 0.5,
        dmg: 120,
        pp: 10,
        dmgtype: 'phy',
    },
    {
        name: 'Baby-Doll Eyes',
        type: 17,
        acc: 100,
        movetype: 'stat',
        effecttype: ['atk'],
        effect: [-1],
        who: ['you'],
        pp: 30,
        priority: 1,
    },
    {
        name: 'Baddy Bad',
        type: 0,
        acc: 100,
        movetype: 'damage',        
        effect2: 'screen',
        screentype: 'reflect',
        dmg: 80,
        pp: 15,
        dmgtype: 'spe',
    },
    {
        name: 'Baneful Bunker',
        type: 7,
        acc: 0,
        movetype: 'banefulbunker',
        priority: 4,
        pp: 10,
    },
    {
        name: 'Barb Barrage',
        type: 7,
        acc: 100,
        movetype: 'barbbarrage',
        dmg: 60,
        pp: 10,
        effect2: 'status',
        statustype: 'brn',
        effect: true,
        dmgtype: 'phy',
    },
    {
        name: 'Barrage',
        type: 0,
        acc: 85,
        movetype: 'multidmg',
        dmg: 15,
        dmgtype: 'phy',
        pp: 20,
    },
    {
        name: 'Barrier',
        type: 10,
        acc: 0,
        movetype: 'stat',
        effecttype: ['def'],
        effect: [2],
        who: ['me'],
        pp: 20,
    },
    {
        name: 'Baton Pass',         // må imlpementere alt som kan påvirke det først
        type: 0,
        acc: 100,
        movetype: 'damage',
        dmg: 40,
        pp: 35,
        dmgtype: 'phy',
    },
    {
        name: 'Beak Blast',             // Wtf
        type: 0,
        acc: 100,
        movetype: 'damage',
        dmg: 40,
        pp: 35,
        dmgtype: 'phy',
    },
    {
        name: 'Beat Up',
        type: 15,
        acc: 100,
        movetype: 'beatup',
        dmg: null,
        pp: 10,
        dmgtype: 'phy',
    },
    {
        name: 'Behemoth Bash',     
        type: 16,
        acc: 100,
        movetype: 'behemoth',
        dmg: 100,
        pp: 5,
        dmgtype: 'phy',
    },
    {
        name: 'Behemoth Blade',     
        type: 0,
        acc: 100,
        movetype: 'behemoth',
        dmg: 100,
        pp: 35,
        dmgtype: 'phy',
    },
    {
        name: 'Belch',
        type: 0,
        acc: 90,
        movetype: 'belch',
        dmg: 120,
        pp: 10,
        dmgtype: 'spe',
    },
    {
        name: 'Belly Drum',
        type: 0,
        acc: 0,
        movetype: 'bellydrum',
        pp: 10,
    },
    {
        name: 'Bestow',
        type: 0,
        acc: 0,
        movetype: 'bestow',
        pp: 15,
    },
    {
        name: 'Bide',
        type: 0,
        acc: 0,
        movetype: 'bide1', 
        pp: 15,
        priority: 1,
        turn2: {
            name: 'Bide',
            type: 0,
            acc: 0,
            movetype: 'bide2',
            priority: 1,
            turn2: {
                name: 'Bide',
                type: 0,
                acc: 0,
                movetype: 'bide3',
                priority: 1,
            }
        }
    },
    {
        name: 'Bind',
        type: 0,
        acc: 0,
        movetype: 'bind', // må teste om de stacker
        pp: 15,
    },
    {
        name: 'Bite',
        type: 15,
        acc: 100,
        movetype: 'damage',
        dmg: 60,
        effect2: 'flinch',
        acc2: 20,
        dmgtype: 'phy',
        pp: 10,
    },
    {
        name: 'Bitter Blade',
        type: 1,
        acc: 100,
        movetype: 'dmgheal',
        dmg: 90,
        pp: 10,
        dmgtype: 'phy',
        value: 0.5,
    },
    {
        name: 'Black Hole Eclipse',     // må implemente z moves
        type: 0,
        acc: 100,
        movetype: 'damage',
        dmg: 40,
        pp: 35,
        dmgtype: 'phy',
    },
    {
        name: 'Bitter Malice',
        type: 13,
        acc: 100,
        movetype: 'damage',
        dmg: 75,
        effect2: 'stat',
        acc2: 100,
        crit: 0,
        effecttype: ['atk'],
        effect: [-1],
        who: ['you'],
        dmgtype: 'phy',
        pp: 10,
    },
    {
        name: 'Blast Burn',
        type: 1,
        acc: 90,
        movetype: 'damage',
        turn2: {
            movetype: 'recharge'
        },
        dmg: 150,
        pp: 35,
        dmgtype: 'phy',
        pp: 5,
    },
    {
        name: 'Blazing Torque',
        type: 0,
        acc: 100,
        movetype: 'damage',
        dmg: 80,
        pp: 10,
        dmgtype: 'phy',
        acc2: 30,
        effect2: 'status',
        statustype: 'brn',
        effect: true,        
    },
    {
        name: 'Bleakwind Storm',
        type: 9,
        acc: 80,
        movetype: 'damage',
        dmg: 100,
        dmgtype: 'spe',
        pp: 10,
        effect2: 'stat',
        acc2: 30,
        effecttype: ['spe'],
        effect: [-1],
        who: ['you'],
    },
    {
        name: 'Blizzard',
        type: 3,
        acc: 70,
        movetype: 'damage',
        dmg: 110,
        pp: 5,
        dmgtype: 'spe',
        acc2: 10,
        effect2: 'status',
        statustype: 'frz',
        effect: true,        
    },
    {
        name: 'Block',
        type: 0,
        acc: 0,
        movetype: 'trapped',
        pp: 5,
    },
    {
        name: 'Tackle',
        type: 0,
        acc: 100,
        movetype: 'damage',
        dmg: 40,
        pp: 35,
        dmgtype: 'phy',
    },
    {
        name: 'Growl',
        type: 0,
        acc: 0,
        movetype: 'stat',
        effecttype: ['atk'],
        effect: [-1],
        who: ['you'],
        pp: 10,
    },
    {
        name: 'U Turn',
        type: 11,
        acc: 100,
        movetype: 'damage',
        effect2: 'switchuser',
        acc2: 0,
        dmg: 70,
        pp: 35,
        dmgtype: 'phy',
        pp: 10,
    },
    {
        name: 'Protect',
        type: 0,
        acc: 0,
        movetype: 'protect',
        priority: 4,
        pp: 10,
    },
    {
        name: 'Rock Blast',
        type: 12,
        acc: 90,
        movetype: 'multidmg',
        dmg: 25,
        dmgtype: 'phy',
        pp: 20,
    },
    {
        name: 'Giga Impact',
        type: 0,
        acc: 90,
        movetype: 'damage',
        turn2: {
            movetype: 'recharge'
        },
        dmg: 150,
        pp: 35,
        dmgtype: 'phy',
        pp: 10,
    },
    {
        name: 'Fly',
        type: 9,
        movetype: 'invul',
        pp: 10,
        acc: 100,
        turn2: {
            name: 'Fly',
            type: 9,
            dmg: 90,
            acc: 95,
            movetype: 'damage',
            dmgtype: 'phy',
        },
    },
    {
        name: 'Toxic',
        type: 7,
        acc: 0,
        movetype: 'status',
        statustype: 'tox',
        effect: true,
        pp: 10,
    },
    {
        name: 'Power Up Punch',
        type: 6,
        acc: 0,
        movetype: 'damage',
        dmg: 40,
        effect2: 'stat',
        acc2: 100,
        crit: 0,
        effecttype: ['atk'],
        effect: [1],
        who: ['me'],
        dmgtype: 'phy',
        pp: 15,
    },
    {
        name: 'Recover',
        type: 0,
        acc: 0,
        movetype: 'heal',
        healtype: '%',
        heal: 0.5,
        pp: 10,
    },
    {
        name: 'Quick Attack',
        type: 0,
        acc: 100,
        movetype: 'damage',
        dmg: 40,
        acc: 100,
        priority: 1,
        dmgtype: 'phy',
        pp: 10,
    },
    {
        name: 'Swords Dance',
        type: 0,
        acc: 0,
        movetype: 'stat',
        effecttype: ['atk'],
        effect: [2],
        who: ['me'],
        pp: 10,
    },
    {
        name: 'Explosion',
        type: 0,
        dmg: 250,
        acc: 100,
        acc2: 0,
        movetype: 'damage',
        effect2: 'suicide',
        dmgtype: 'phy',
        pp: 10,
    },
    {
        name: 'Smokescreen',
        type: 13,
        acc: 0,
        movetype: 'stat',
        effecttype: ['acc'],
        effect: [-1],
        who: ['you'],
        pp: 10,
    },
    {
        name: 'Will o Wisp',
        type: 1,
        acc: 85,
        movetype: 'status',
        statustype: 'brn',
        effect: true,
        pp: 10,
    },
    {
        name: 'Sandstorm',
        type: 3,
        acc: 0,
        movetype: 'weatherchange',
        weather: 'sandstorm',
        pp: 10,
    },
    {
        name: 'Rain Dance',
        type: 2,
        acc: 0,
        movetype: 'weatherchange',
        weather: 'rain',
        pp: 10,
    },
    {
        name: 'Lunar Dance',
        type: 0,
        acc: 0,
        movetype: 'statusheal',
        statustype: '',
        effect: false,
        pp: 10,
    },
    {
        name: 'Curse',
        type: 13,
        acc: 0,
        movetype: 'stat',
        effecttype: ['spe', 'atk', 'def'],
        effect: [-1, 1, 1],
        who: ['me', 'me', 'me'],
        pp: 10,
    },
    {
        name: 'Rock Throw',
        type: 12,
        acc: 90,
        movetype: 'damage',
        dmg: 50,
        dmgtype: 'phy',
        pp: 10,
    },
    {
        name: 'Spikes',
        type: 8,
        acc: 0,
        movetype: 'sethazard',
        effect: 'spk',
        pp: 20,
    },
    {
        name: 'Toxic Spikes',
        type: 7,
        acc: 0,
        movetype: 'sethazard',
        effect: 'tspk',
        pp: 20,
    },
    {
        name: 'Stealth Rock',
        type: 12,
        acc: 0,
        movetype: 'sethazard',
        effect: 'strk',
        pp: 20,
    },
    {
        name: 'Sticky Web',
        type: 11,
        acc: 0,
        movetype: 'sethazard',
        effect: 'stwb',
        pp: 20,
    },
    {
        name: 'Solar Beam',
        type: 3,
        movetype: 'charge',
        turn2: {
            name: 'Solar Beam',
            type: 3,
            dmg: 120,
            acc: 100,
            movetype: 'damage',
            dmgtype: 'spe',
            pp: 20,
        }
    },
    {
        name: 'Dig',
        type: 8,
        dmg: 80,
        acc: 100,
        movetype: 'damage',
        effect: 'invulthendmg',
        pp: 20,
    },
    {
        name: 'Confuse Ray',
        type: 13,
        acc: 100,
        movetype: 'confuse',
        pp: 20,
    },
    {
        name: 'Trick Room',
        type: 10,
        acc: 0,
        movetype: 'trickroom',
        pp: 5,
        priority: -7,
    },
    {
        name: 'Double Edge',
        type: 0,
        dmg: 120,
        acc: 100,
        movetype: 'damagewithrecoil',
        effect: 0.33,
        pp: 20,
    },
]

