let pokemon = [
    {
        name: "Dwebble",
        avatar: `<img style="height: auto; width: 20vh" src="media/pictures/pokemon/dwebble.png" alt="">`,
        url: 'media/pictures/pokemon/dwebble.png',
        maxhp: 10000,
        hp: 10000,
        atk: 10,
        def: 10,
        spa: 10,
        spd: 10,
        spe: 10,
        status: '',
        move: [64, 7, 9, 3],
        pp: [],
        type1: "Rock",
        type2: "Bug",
        sex: 'male',
        weight: 14.5, 
        ability: JSON.parse(JSON.stringify(abilities[1])),
        item: JSON.parse(JSON.stringify(items[0])),
        id: 0,
    },
    {
        name: "Charmander",
        avatar: `<img style="height: auto; width: 20vh" src="media/pictures/pokemon/charmander.png" alt="">`,
        url: 'media/pictures/pokemon/charmander.png',
        maxhp: 3,
        hp: 3,
        atk: 11,
        def: 8,
        spa: 13,
        spd: 10,
        spe: 1,
        status: '',
        move: [1, 1, 1, 1],
        pp: [],
        type1: "Fire",
        type2: "Null",
        sex: 'male',
        weight: 14.5, 
        ability: JSON.parse(JSON.stringify(abilities[1])),
        item: JSON.parse(JSON.stringify(items[0])),
        id: 1
    },
    {
        name: "kek",
        avatar: `<img style="height: auto; width: 20vh" src="media/pictures/pokemon/charmander.png" alt="">`,
        maxhp: 3,
        hp: 3,
        atk: 11,
        def: 8,
        spa: 13,
        spd: 10,
        spe: 1,
        status: '',
        move: [2, 2, 2, 2],
        pp: [],
        type1: 1,
        type2: 18,
        sex: 'female',
        weight: 14.5, 
        ability: JSON.parse(JSON.stringify(abilities[1])),
        item: null,
        id: 2
    },
]